export const GACHA = {
  COST: 500,
  PITY_EPIC: 10,
  PITY_LEGENDARY: 50,
};

export const JADE = {
  BASE_REWARD: 100,
  WORLD_CLEAR_BONUS: 500,
  WORLD_CLEAR_NG_SCALE: 200,
  BOSS_HIT_BASE: 800,
  TREASURE_BASE: 200,
  TREASURE_RANGE: 100,
  TREASURE_WORLD_SCALE: 50,
};

export const BOSS = {
  QUESTIONS_PER_BOSS: 3,
  TIMER_MIN: 15,
  NG_HP_BONUS: 1,
  NG_TIMER_REDUCTION: 3,
  NG_JADE_BONUS: 200,
  NG_LOOT_MIN_BONUS: 300,
  NG_LOOT_MAX_BONUS: 500,
  NG_COMPANION_CHANCE_BONUS: 5,
  MAX_COMPANION_CHANCE: 80,
};

export const STREAK = {
  MILESTONES: [5, 10, 15, 20, 25] as const,
  FIRE_MODE_THRESHOLD: 5,
  SHIELD_PROTECTS_ONCE: true,
};

export const QUESTIONS = {
  PER_NODE: 5,
  PER_BOSS: 3,
  BATCH_SIZE: 10,
};

export const ACHIEVEMENTS = {
  DISPLAY_MS: 3000,
  GAP_MS: 300,
};

export const DAILY_REWARDS = {
  DAYS_IN_CYCLE: 7,
};

export const SYNC = {
  DEBOUNCE_MS: 3000,
  RETRY_MAX: 3,
  RETRY_BASE_DELAY: 1000,
};

export const AUDIO = {
  TTS_TIMEOUT_MS: 10000,
  DEFAULT_VOICE: 'zh-CN-XiaoxiaoNeural',
  DEFAULT_SPEED: 0.75,
  DEFAULT_BGM_VOLUME: 0.1,
  DEFAULT_SFX_VOLUME: 0.7,
};
